### ISSUE TITLE
Key not used in 4 lines of xml

### ISSUE THREAD

**Issue by ot2sen** [lucid-fox/social-magick#15]
In socialmagick.xml the raw text is used instead of language keys for:

259 label="Should the image be full-width and full-height?"
260 description="Anything larger than your specified dimensions will be resized and cropped to fit."
293 label="Image Position (pixels from left edge)"
302 label="Image Position (pixels from top edge)"

**Comment by nikosdion** [comment]
Thank you for the heads up!
