### ISSUE TITLE
Build file naming

### ISSUE THREAD

**Issue by ot2sen** [lucid-fox/social-magick#16]
**Describe the solution you'd like**
"Feature" Probably because of beta state, but would be nice with plg_system_vernr_ in the downloadable release build.
The b1 and b2 looked much alike :)

Btw. this tool looks useful. Nice touch with the auto-generate imgs. Thumbs up!

**Comment by nikosdion** [comment]
Yup, I had the same thought :) We'll implement it for the next release.
