### ISSUE TITLE
Just by refreshing the Facebook debugger, the og:image (which was right) changes

### ISSUE THREAD

**Issue by woluweb** [lucid-fox/social-magick#27]
### Steps to reproduce the issue

Hi,

I have been trying to play and understand this issue for a couple of hours but I'm becoming crazy :)
Same issue applies on two websites (one with OVH and the other one with PlanetHoster).

Actually you can see what's happening in this very short video:
https://www.loom.com/share/3c48f27096ca44d99f99c6d71e2cd04f

Social Magick is installed.
I enable the plugin, I use Cutout but I have customized the transparent cutout image.
I enable Social Magick on a menu item and choose Cutout, I select "intro image".

Then going to Facebook Debugger, it first works.
Then I refresh the Facebook Debugger and the og:image changes : 
- the intro image disappears
- and instead of Article TitIe get Browser Title

### Troubleshooting already performed

But then I have finally discovered something: if I clear the Joomla cache (in my case using Cache Cleaner by Regular Labs), then
- when I refresh the Facebook Debugger the correct og:image appears ! Good news :)
- but again if I refresh again the wrong og:image is shown. Bad news :(

Do you have any clue of what could cause this issue?

(I had first thought it was caused by the fact that I had created a new profile in the plugin and also changed order. But even uninstalling and then only editing the default profiles would lead to the same issue)

#### Mandatory information

* **Joomla! version**: 3.9.26
* **PHP version**: 7.4.15
* **Server Operating System**: Linux
* **The URL to the page where you are having a problem**: https://www.lesenfantsdesalus.be/fr/a-propos/missions
* **Are you using GD, Imagick or don't know?**: It was set on "auto". Then I tried setting "Imagick" but issue would be the same
* **Imagick and GD versions as reported by `phpinfo()` on your site:** Imagick 3.4.4 GD 2.9.1

**Comment by nikosdion** [comment]
This sounds like a Joomla caching issue. I suspect that onContentBeforeDisplay may not be fired for your cached article which would cause the plugin's main event (onBeforeDisplay) to fall back to the default Social Magick profile.

So, let's try to get some more information to reproduce this issue.

Are you using progressive or conservative caching?

Is it file caching or something else? if so, please specify.

Do you have the System - Cache plugin enabled and, if so, what are its settings?

Are you using a CDN or anything similar which could also be applying its own caching? (Shouldn't be relevant but I want to have all my bases covered)

**Comment by woluweb** [comment]
Txs for the very quick follow-up, Nicholas!

Note: I also tried to put the Social Magick first and then last of the System plugins, just in case it would have played a role. But same issue.

Here is the configuration
- Cache Handler: File
- Cache Time: 15
- Platform Specific Caching: No
- System Cache: Progressive for the one of the video and Conservative for the other site
- System - Page Cache : is disabled on both sites.
- No CDN

In the meantime I have tested further now that you gave that idea of some interference with Caching.
Interesting conclusion: on both website:
- if I completely disable Caching in Global Configuration then the issue does not arise!
- if I re-enable Caching (progressive on one site, conservative on the other) again the issue arises at the second Recollect on Facebook Debug's page

Does this help you to figure out what the issue can be?
I can of course give you (super user) access to the website(s) if it makes it faster/easier for you to reproduce/check.

Txs again

**Comment by woluweb** [comment]
(btw, is it normal that Facebook debugger says (I translate): "The following required properties are missing : og:url, og:type, og:title, og:description, fb:app_id"?

**Comment by nikosdion** [comment]
Hm, I can't reproduce it with the current code. I'm also a bit confused as to why it happens. The workaround for the caching issue is already in beta 2. My guess is that one of the changes I made after beta 2 may have fixed whatever issue you are hitting. I will issue a beta 3 in a short while.

Regarding your other question, yes, these OpenGraph properties are missing. Beta 3 adds options to generate them for you :) Facebook will still complain because you don't have a fb:app_id (you really don't _need_ to set it unless you have a Facebook application linked to your site). It will work regardless.

I am leaving this issue open until you can test with beta 3.

**Comment by woluweb** [comment]
Txs again Nicholas,

Fine, I'll be happy to test this with Beta 3!

As to fb:app_id: indeed we don't care about that one. But happy to know that the other OpenGraph properties will be there :)

Looking forward to Beta 3 then ;)

**Comment by nikosdion** [comment]
Already released :)

**Comment by woluweb** [comment]
That was quick!
Txs a lot.

I have tested but that does not solve the issue: whith caching off (or when cache is cleaned),
- the og:image is correct when loading a page for the first time
- but then when refreshing the page the og:image gets regenerated without the intro_image

**Comment by nikosdion** [comment]
This is really weird. I need a backup of that site so I can test this locally. There seems to be more than just the Joomla caching in play.

Here's the problem: how can you give me the connection information I need when GitHub only allows public issues. I have a solution for that. 

Go to https://keybase.io/encrypt and in the recipient field type `nikosdion`. You should see my face and my info. Click on that. In the “Message to Encrypt” field type in the following information:

* URL to your site's administrator login page, e.g. `https://www.example.com/administrator/index.php?foobar`
* HTTP authentication username (if applicable):
* HTTP authentication password (if applicable):
* Joomla username:
* Joomla password:
* (S)FTP connection type (FTP or SFTP):
* (S)FTP hostname:
* (S)FTP port:
* (S)FTP username:
* (S)FTP password:

**Note**: If possible, make sure that the Joomla and (S)FTP credentials you are sending me are _temporary_ and you can revoke them when I tell you I'm done.

Click on Encrypt. Copy the scrambled (encrypted) text, paste it into a text file with an extension .asc and attach that file to your next reply to the GitHub issue. I am the only one who can decrypt this using my private GPG key in my YubiKey hardware. I will log into your site, install Akeeba Backup (if it's not already installed), take a backup and download it locally so I can do further testing. After I am done testing I destroy the restored site and the backup copy and will let you know so you can revoke my access to your site.

I've tried the Keybase encryption thing in the past and it should work fine. It's far more secure than sending credentials by email and has the added benefit that the credentials are on the same issue I am working on so I don't have to try and correlate emails and GitHub issues.

**Comment by woluweb** [comment]
Hi Nicholas,

This reminds me of Pretty Good Privacy which I used in the early nineties with Eudora or Pegasus as mail client :)

I went to https://keybase.io/encrypt, chose your profile, saw your face... but when I click on the Encrypt button I get the following error msg:
`Error: Recipient does not have any active encryption keys.`

**Comment by nikosdion** [comment]
About a year ago (June 2020) my then current GPG key was expiring. I updated they key in Keybase following their instructions on doing it over their web interface. The same key material is also on my site and definitely works — I've received GPG-encrypted emails. Guess what? Keybase didn't like me following their instructions. I had to use their command line client to update my key... I did it just now so you should be able to give it another go and this time it will work (I checked).

**Comment by woluweb** [comment]
:D 
txs for the hassle ;)

Here is the file:
[nikosdion-marc.txt](https://github.com/lucid-fox/social-magick/files/6448228/nikosdion-marc.txt)

Note: Github does not accept .asc so I choose .txt :)

**Comment by nikosdion** [comment]
Thank you for the info! I was able to reproduce and fix this issue. Please find a development version attached so you can test it yourself.

[socialmagick-rev97FBCA7.zip](https://github.com/lucid-fox/social-magick/files/6484960/socialmagick-rev97FBCA7.zip)

**Comment by woluweb** [comment]
Txs @nikosdion!
I have installed that dev version on my two sites where I had the issue and everything seems to go fine so far :)

Txs a lot for the fix.
(btw, was it linked to the way I configure Joomla or was it a more general issue?)

**Comment by nikosdion** [comment]
It was actually a typo. I had typed `??` instead of `?:`. Whether it triggered a different behaviour or not depended on the category options and menu item type. You had an article menu item, I had only tested with category menu items.

It was one of those things that take you an hour to set up the debugging, 5 minutes to realise what's going on and 5 second to fix...
