### ISSUE TITLE
xml of beta3 says beta2 (so Joomla Update Manager loops) + issue with download link

### ISSUE THREAD

**Issue by woluweb** [lucid-fox/social-magick#29]
**1.**
After installing beta3, Joomla Update Manager keeps saying that an update is available.
And indeed, in Extensions > Manage it says that the installed version is beta2.
I have checked: the xml file of the package has simply not been adapted.

**2.**
Besides this, the Joomla throws an error when updating:
```
Warning
Update: :Extension: Could not open
Error
Invalid extension update
```
And indeed the link given is
https://github.com/lucid-fox/social-magick/releases/1.0.0.b3/socialmagick.zip
while the file name is this time not socialmagick.zip but socialmagick-1.0.0.b3.zip

**Comment by nikosdion** [comment]
1. That's the cache in Joomla
2. Oops, I'll fix the XML update file!

**Comment by woluweb** [comment]
Txs Nicholas!

Just to be clear, there are 2 different things to fix I think:

1. for the download link, the name of the file but also the /releases/ which was missing in the url:
`https://github.com/lucid-fox/social-magick/releases/1.0.0.b3/socialmagick.zip`
=>
`https://github.com/lucid-fox/social-magick/releases/download/1.0.0.b3/socialmagick-1.0.0.b3.zip`

2. for the version in the xml, b3 is still called b2:
`<version>1.0.0.b2</version>`
=>
`<version>1.0.0.b3</version>`

**Comment by woluweb** [comment]
Txs Nicholas,

Actually, I was not even speaking of Joomla: 
What I simply meant is that (even now) In the Zip file of release b3 I read
<version>1.0.0.b2</version>
:)

So afaik, when you install b3 Joomla will keep thinking that you have b2 installed even if it is b3 :)

**Comment by nikosdion** [comment]
Ah, I am used to my own releases where the version bump automatically. I fixed it now.

**Comment by woluweb** [comment]
;)
