### ISSUE TITLE
Newsflash module on J4 overrides open graph output on article page

### ISSUE THREAD

**Issue by crystalenka** [lucid-fox/social-magick#31]
### Steps to reproduce the issue

1. Create a J4 site with at least two articles in two different categories.
2. On one article, place a newsflash module showing articles from the other category.

### Expected result

Social Magick generates an image with the title and settings from the article that is on the page.

### Actual result

Social Magick generates an image with the title and settings from the article that is in the newsflash module.

### Troubleshooting already performed

Unpublishing the module or the article from inside it removes the behavior.

Turning off social magick image generation from the newsflash module's selected category turns it off for the whole page.

#### Mandatory information

* **Joomla! version**: 4.0.2
* **PHP version**: 8.0.9
* **Server Operating System**: Linux
* **The URL to the page where you are having a problem**: https://www.whatt.eu/en/blogs-podcasts/blog-1 as reported by @woluweb
* **Are you using GD, Imagick or don't know?**: Unsure
* **Imagick and GD versions as reported by `phpinfo()` on your site:** GD 2.2.5

#### Good to have information

* **Hosting company / Local server**: Ask @woluweb :)
* **Local server version**: 
* **Server Operating System version**: 

### Additional comments
Originally reported by @woluweb via Facebook Messenger.

Possibly related is J4 not pulling in intro or full text images into generated images.

**Comment by woluweb** [comment]
Exactly. That is the first thing.
I will also add that if that newsflash module is unpublished, the text becomes correct again... even if there is in fact still another newsflash module on the right.

Then there seems also to be an issue with the images:
- I did not manage to display neither intro or full image on the og:image
- and for the Template that I duplicated from my J!3 website where it works, the result is a black image instead (and not using my image https://www.whatt.eu/images/opengraph.png as basis)
