### ISSUE TITLE
getting "This plugin .is not compatible with Joomla 4.1 or later"

### ISSUE THREAD

**Issue by woluweb** [lucid-fox/social-magick#33]
Hi Crystal & Nicholas,
I'll be happy to test if a new beta version gets released :)

### Steps to reproduce the issue

Install latest version (1.0.0.b4) on J4.1

### Expected result

Installation successful

### Actual result

Following error msg displayed
`This plugin .is not compatible with Joomla 4.1 or later.
Extension Install: Custom install routine failure.`

#### Mandatory information

* **Joomla! version**: 4.1
* **PHP version**: 8.0

**Comment by nikosdion** [comment]
Check release 1.0.0 stable

**Comment by woluweb** [comment]
Txs @nikosdion!
Indeed it now installs properly on J4.1 :)

**Comment by woluweb** [comment]
oh, btw, now that I am testing it: it seems that nor the intro img nor the full img is pulled behind the overlay.png.
See for example this test page: https://dev.festivalmusiq3.be/concerts/bruxelles/misia-sert-reine-de-paris
Is it just me?
Or could it be some side-effect?

**Comment by nikosdion** [comment]
Yup, there was a bug with the new image link format Joomla applied. This and the other issue you reported are now fixed in version 1.0.1.
