### ISSUE TITLE
error on Acymailing front-end newsletters when having SocialMagick installed

### ISSUE THREAD

**Issue by woluweb** [lucid-fox/social-magick#34]
### Steps to reproduce the issue

- Install Acymailing,
- Have a first newsletter
- Publish a front-end Menu Item to the Newsletters archives 
- Click on the link to one of the newsletters

### Expected result
No error
### Actual result

Getting the following error: 
LucidFox\SocialMagick\ParametersRetriever::getCategoryArticleParameters(): Argument #1 ($id) must be of type int, null given, called in /home/festivalki/dev/plugins/system/socialmagick/library/ParametersRetriever.php on line 180

### Troubleshooting already performed

When adding &format=raw to the url (which is actually the url that you get when clicking on the "read in my browser" link in the newsletter itself), then only the Newsletter is shown *without* any of the Joomla stuff (Menu, ...) and so there is no error message.

So to give an example:
- error msg with: https://dev.festivalmusiq3.be/component/acym/archive/32-festival-musiq3-exemple-de-newsletter-avant-personnalisation?tmpl=raw
- everything OK with: https://dev.festivalmusiq3.be/component/acym/archive/32-festival-musiq3-exemple-de-newsletter-avant-personnalisation?tmpl=raw&format=raw

I don't know if the issue is only with Acymailing for example or if it would occur for any third-party component (which does not have the Category ID or Item ID like for articles.

I wanted to disable SocialMagick on the Newsletter Menu Item, but the first switch only allows to choose between
- Inherit
- and Yes
(can this be that there is no "No" option btw?)

As a quick workaround for this issue I have installed ReReplacer and I replace
´?tmpl=raw`
by
?tmpl=raw&format=raw`
(so that my end users can test the development website)

### System information

* **Joomla! version**: 4.1
* **PHP version**: 8.0

### Other Comments

Txs :)
And of course I'll be happy to test any fix as usual.

**Comment by woluweb** [comment]
Once again txs a lot Crystal & Nicholas for the bug fixes and for the new release.
I do confirm: 
1. no crash any more on Acymailing's page
2. about the og image : the article image does now indeed appear behind the mask
So everything solved :)
Txs again,
Marc

**Comment by nikosdion** [comment]
Go to extension updates and click on the reset cache button. The update should work correctly now. Installing it will fix the problem with the update being continuously found.
