### ISSUE TITLE
Possibility to manually Select an Image for Menu Items and for Categories

### ISSUE THREAD

**Issue by woluweb** [lucid-fox/social-magick#35]
**What is the use case of your proposed feature?**
SocialMagick works fine on Article pages.
But when I wanted to select an image for
- a Menu Item of Type Blog
- a Menu Item of Type Featured
- a Menu Item of any Type other than Single Article actually
I realized that I could not select/configure any image bc there are 4 choices, namely
- none
- intro img
- full img
- custom field

I even looked at the Category, but there also we only see those 4 options

**Describe the solution you'd like**
After chatting on Messenger with Crystal to confirm that I had not missed some obvious option, she confirmed that it was not possible with the current version.
So I suggested the following, which seems to me to be quite universal (would work of any type of Menu Item and also on Categories) : 
simply add a 5th option being "select file"

Note: Crystal was wondering about Menu Cascading. Actually, this is another topic. If we can already set manually each level of Menu Item, we are fine. I am not asking for Cascading

**Why do you think this is relevant to people other than you?**
Well, Blog views (or Featured) is quite typical on websites, especially for the homepage (and elsewhere of course).
So it is a bit paradoxical that we would have an og:image for the Articles but not for the rest of the site
With other words, the plugin would be more universal.
It is a common usecase.

**Comment by woluweb** [comment]
Besides I was wondering: in a Menu Item for example the Option `Generate Open Graph images` gives two choices
- inherit
- yes
Wouldn't it make sense to add `no` as well ?
(then one could choose Yes in the general configuration of the plugin but make an exception for some page(s) )

**Comment by woluweb** [comment]
Txs! Exciting times :)

**Comment by woluweb** [comment]
Txs a lot for 1.0.2!
Tested successfully :)

It works perfectly for all Types of Menu Items.
There is just one side-effect that I had not anticipated.
Above I had said that cascading was not important (in the sense of a submenu inheriting the configuration of its parent). I still stick to that.

The main goal of having "static image" for Blog View was to be able to have an og:image for the Blog View as well, not only for the corresponding Articles.
But here I realize that
- when select a Static Image for the Blog View
- then all corresponding Articles also take that Static Image (and not for example the Full Image)

**Comment by nikosdion** [comment]
Yes, that is the only possible way this can work. Otherwise you'd have to override each and every article. Remember the menu item ID in a category view is **always the same** no matter if you are viewing the list of items or each individual item.

As I have [already explained in our documentation](https://github.com/lucid-fox/social-magick/wiki/Rejected-features#support-for-third-party-extensions-ccks-page-builders-and-so-on) we are not going to add features which require knowing how each extensions works for the simple reason that you can create template overrides, as Crystal already told you on Messenger.

In this case, you'd assign the SocialMagick template **for the articles** to the menu item. In your **category list / blog view** template override you can override the SocialMagick template so that the blog view page _and only that page_ uses that different template:

```php
\Joomla\CMS\Menu\AbstractMenu::getInstance()->getActive()->getParams()->set('socialmagick.template', 'A Different Template Here');
```

You can of course override specific parameters instead of assigning a different template as per the link above.

**Comment by woluweb** [comment]
Txs for the clarification @nikosdion!

You understand SocialMagick (and Joomla in general and coding :D ) much better than I do :)

So am I summarizing it correctly that
1.  in the Menu Item of Type Blog, I can leave the setting of the SocialMagick on "full image" so that all the Single Article View will take that parameter automatically
2. but in my override of the Blog View, I should add the line of code you are quoting so that the Blog View can have a Static Image
?

If so, I understand the idea and it is indeed easy to implement.

But still *in practice* I am not sure of what the following line should then become in my Blog View override :)
`\Joomla\CMS\Menu\AbstractMenu::getInstance()->getActive()->getParams()->set('socialmagick.template', 'A Different Template Here');`

(and actually, to improve on that idea, I suppose I could actually add that line of code in a Module Override, so that I could assign that Module to all Menu Items of Type "Blog", with the same common image)

**Comment by nikosdion** [comment]
1 & 2. Yes.

`A Different Template Here` is the name of a different SocialMagick template. You are in control of that name, I can't give you that.

About module overrides. Modules are loaded _per active menu item_ therefore in article sub-pages as well. This is the same problem you are trying to solve. That's a whole lot of work to achieve... nothing?
