### ISSUE TITLE
Can  Extra image source be a global setting?

### ISSUE THREAD

**Issue by coolcat-creations** [lucid-fox/social-magick#36]
**What is the use case of your proposed feature?**
I want always the intro images to be the source for the cutout template and there is a setting in the article but I have to set it everywhere separately to make it work.

**Describe the solution you'd like**
It would be good to have this as a global setting?

**Why do you think this is relevant to people other than you?**
Sometimes people do not use the fulltext image at all

thanks :)

Please note that feature requests will be considered but there is no guarantee that they will be implemented within any
specific time frame or at all. It is ultimately up to our discretion. If you believe that you can implement the requested
feature yourself please do say so in your issue.

**Comment by crystalenka** [comment]
Hi Elisa!!

Thank you for the suggestion :)

In the past when we had this question this was @nikosdion reply:

> ...you can have a default at the category level. This makes far more sense than a global default. If you really want a global default there's a standard Joomla way to do it. Create a root category which itself has no articles and batch process all of your existing top level categories, moving them into it. Now your root category can be assigned default options and they can be overridden in each child category. Still, this is a bit icky and likely to catch you by surprise. It's best to spend 5' to set up the default per category than waste a day trying to figure out where the bloody image is coming from six months after delivering a site.

However, I am reconsidering now whether an (optional) default at the template level makes sense, because it can also be overridden in a category when necessary for more complex sites. I will take a look when I can, but right now I'm a little snowed under.

Thank you!

**Comment by crystalenka** [comment]
No worries!! I'm glad it's helpful for you :) 

I really must finish up that documentation so these things are clearer....eventually...sorry!!!

Have a wonderful day!
