### ISSUE TITLE
update > your current database MySQLi is not supported anymore

### ISSUE THREAD

**Issue by woluweb** [lucid-fox/social-magick#37]
### Steps to reproduce the issue

I go to the Update Manager, click on the Update button

### Expected result

I expect nothing special...

### Actual result

... but I get a yellow notification saying
`For the extension Social Magick version 1.0.2 is available, but your current database MySQLi is not supported anymore.`

### Troubleshooting already performed

Please tell us about any troubleshooting you already performed and its results.

#### Mandatory information

* **Joomla! version**: 4.1.5
* **PHP version**: 8.0.3
* **Server Operating System**: Linux 

#### Good to have information

* **Hosting company / Local server**: Linux node13-fr.n0c.com
database type: mysql

### Additional comments

Actually I don't know what this warning message really means (I don't have it with Akeeba Backup or Admin Tools on the same sites for example).
And I see nothing in the readme.md nor on the Release Page about supported/non supported versions or about mysqli.

So what can I do to fix this? And what does happen if I can't fix this?

**Comment by nikosdion** [comment]
You found a Joomla bug. Actually, there are two bugs. First of all, Joomla does not check the supported database family correctly (it tries to match a lowercase to an uppercase string and fails) **and** then it prints out an error message using the database _connector_ type instead of the database _server_ type.

I am closing this issue and reporting this to Joomla.

**Comment by woluweb** [comment]
Txs a lot Nicholas,
But so does it mean that everything is fine with Social Magick and my sites ? (total false positive)

**Comment by nikosdion** [comment]
Nothing is wrong with your site. It's just Joomla: https://github.com/joomla/joomla-cms/issues/38117

There's a military term for that: SNAFU (Situation Normal; All F... Up)
