### ISSUE TITLE
Add options to add other OG tags

### ISSUE THREAD

**Issue by crystalenka** [lucid-fox/social-magick#4]
For this to be a complete magical social solution there should be settings in the backend to automatically set other OG info:

- [x]  `<meta property="og:title" content="**BROWSER PAGE TITLE / OVERRIDE?**">`
- [x]  `<meta property="og:description" content="**META DESCRIPTION / OVERRIDE?**">`
- [x]  `<meta property="og:url" content="**PAGE URL**">`
- [x]  `<meta property="og:site_name" content="** SITE NAME **">`

Also, the option to enable/disable Twitter proprietary tags: (notice the different structure!)
- [x] `<meta name="twitter:title" content="**BROWSER PAGE TITLE / OVERRIDE?**">`
- [x] `<meta name="twitter:description" content="**META DESCRIPTION / OVERRIDE?**">`
- [x] `<meta name="twitter:image" content="**Social Magick Image**">`
- [x]  `<meta name="twitter:image:alt" content="** Social Magick Image Alt **">`
- [x] `<meta name="twitter:card" content="summary_large_image">` —should this be an option?

Finally, should these options be available in the plugin configuration?
- [x] `<meta property="fb:app_id" content="your_app_id" />`
- [x]  `<meta name="twitter:site" content="@website-username">`

**Comment by nikosdion** [comment]
I've been using Git for 10 years. Today my commit disappeared from all repos. What the actual fuck.
