### ISSUE TITLE
1.0.2 update does not work

### ISSUE THREAD

**Issue by toonetcreation** [lucid-fox/social-magick#42]
Hi,

Even if I apply update detected by joomla updater or If I upload ZIP file manually, does not work.
version 1.0.1 is always displayed : https://www.screenpresso.com/=t0MGd

THanks
L.

**Comment by woluweb** [comment]
Yep, same here.
What I did is that I edited the xml file to change 1.0.1 into 1.0.2 myself (then rezipped and installed).

**Comment by toonetcreation** [comment]
thanks for the info @woluweb :-)

If the problem can be solved in the main package, could be nice :)

**Comment by coolcat-creations** [comment]
Same issue here :)

**Comment by crystalenka** [comment]
Hi guys, sorry for the delay. Will take a look!

**Comment by webgras** [comment]
Same issue here :-)

**Comment by crystalenka** [comment]
Thanks for your patience, everyone. Please update to 2.0.0 :)

**Comment by coolcat-creations** [comment]
Wonderful thank you @crystalenka

**Comment by toonetcreation** [comment]
thank you @crystalenka
