### ISSUE TITLE
php compatibility

### ISSUE THREAD

**Issue by toonetcreation** [lucid-fox/social-magick#44]
Hi,

Is Social Magik compatible with php 8.1 and php 8.2 ?

thanks
L.

**Comment by crystalenka** [comment]
Hi! I haven't specifically tested it yet but I can't think of anything which would be incompatible. If you try it, please let me know if you have any errors and I'll make sure it gets fixed. Thank you!

**Comment by woluweb** [comment]
I use Social Magick on 10+ websites, all running on PHP8.1.
So far nobody reported any issue on my side.

**Comment by toonetcreation** [comment]
thank you both for the feedback :-)

**Comment by crystalenka** [comment]
2.0.0 is now released with PHP compatibility up to 8.3. If you spot any bugs please file a new issue. Thank you!

**Comment by toonetcreation** [comment]
many thanks @crystalenka
