### ISSUE TITLE
Error on J5 without the compatibility plugin

### ISSUE THREAD

**Issue by webgras** [lucid-fox/social-magick#45]
### Steps to reproduce the issue

Update to 5.0.0-RC and disable the "compatibility plugin".
Open an article to edit it.

### Expected result
Viewing the edit form without error.

### Actual result
Error:
Class "JFormFieldRadio" not found 
JROOT\plugins\system\socialmagick\fields\fancyradio.php:24
![grafik](https://github.com/lucid-fox/social-magick/assets/10774704/da85760d-3c4f-476f-b2c6-77817749c68d)

Link:
administrator/index.php?option=com_content&view=article&layout=edit&id=137

#### Mandatory information

* **Joomla! version**: Joomla 5.0.0-RC
* **PHP version**: PHP 8.2
* **Server Operating System**: Windows 
* **The URL to the page where you are having a problem**: Localhost
* **Are you using GD, Imagick or don't know?**: don't know
* **Imagick and GD versions as reported by `phpinfo()` on your site:**

#### Good to have information

* **Hosting company / Local server**: Enter the name of your site's hosting company or the prepackaged local server (e.g. MAMP, XAMPP, WAMPServer, ...) that you're using
* **Local server version**: If using a local server package, which version is it?
* **Server Operating System version**: e.g. Windows 10, Ubuntu 16.04, ... Type N/A if it's a live host and you have no idea.

**Comment by nikosdion** [comment]
It has been fixed since 2 weeks ago: https://github.com/lucid-fox/social-magick/commit/f6736472f0515b6ee782086a4d411e1dad8bb368

Don't ask me about releases. Ask Crystal.
